pipeline:
    compile:
        image: microsoft/aspnetcore-build
        commands:
            - sh build.sh
    build-image:
        command: 
            - docker build -t tata480/dotnetcore-container ./Web
